### ISSUE TITLE
Why blast shows no response?

### ISSUE THREAD

**Issue by chqwww** [sanger-pathogens/Artemis#228]
I try to click the blast in artemis, but always no response. The version 12.0 in my old computer works. The new version and old version do not woke on my new computer and on my lab member's. What setting should I change? Thank you.

**Comment by andrewjpage** [comment]
Hi, NCBI recently updated their blast service, moving from http to https. We have updated the source code to reflect this, however we are waiting on the purchase of a certificate so that we can sign our files. When the certificate is available, we will be able to release new JAR files which will rectify this issue. In the interim you can build Artemis if you wish.
Regards,
Andrew
